Попытка завершения реализации теста по добавлению нового пользователя в багтрэкер Мантис Присутствует ошибка > mail = self.app.mail.get_mail(username, password, "[MantisBT] Account registration") E TypeError: get_mail() missing 1 required positional argument: 'subject'