Исправлена  ошибка > mail = self.app.mail.get_mail(username, password, "[MantisBT] Account registration") E TypeError: get_mail() missing 1 required positional argument: 'subject' Реализована проверка через SOAP интерфейс API